<?php

/**
 * @var Magento\Backend\Block\Template $block
 * @var Marketplacer\SellerShipping\ViewModel\Checkout\Onepage\Success\SuccessAdditionalInfo $viewModel
 */

$viewModel = $block->getData('view_model');
$escaper = $viewModel->getEscaper();
?>

<div class="multicheckout success">
    <p><?= $escaper->escapeHtml(__('For successfully order items, you\'ll receive a confirmation email including '.
            'order numbers, tracking information and more details.')) ?></p>
    <?php if ($orderIds = $viewModel->getOrderIds()) : ?>
        <h3><?= $escaper->escapeHtml(__('Successfully ordered'))?></h3>
        <div class="orders-succeed">
            <ul class="orders-list">
                <?php foreach ($orderIds as $orderId => $incrementId) : ?>
                    <li class="shipping-list">
                        <div class="order-id"><a href="<?= $escaper->escapeUrl($viewModel->getViewOrderUrl($orderId)) ?>">
                                <?= $escaper->escapeHtml($incrementId) ?></a>
                        </div>
                        <div class="shipping-item">
                            <span class="shipping-label"><?= $block->escapeHtml(__('From seller:')) ?></span>
                            <span class="shipping-address">
                                <?= $block->escapeHtml($viewModel->getSellerName($orderId)) ?>
                            </span>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
    <?= $block->getChildHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $escaper->escapeUrl($viewModel->getContinueUrl()) ?>"><span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>